### ISSUE TITLE
kymoline.msd not working

### ISSUE THREAD

**Issue by spangeni** [lumicks/pylake#156]
Release 0.8.2 has a function under studying diffusion process "With Pylake, we can calculate the MSD from a KymoLine with a single command:kymolines[0].msd()" [https://lumicks-pylake.readthedocs.io/en/latest/examples/cas9_kymotracking/cas9_kymotracking.html#id1] with possibility to track the diffusion of all the kymolines as illustrated in the given link.There exists the definition for the class Kymoline,page 177 of https://lumicks-pylake.readthedocs.io/_/downloads/en/latest/pdf/.However,when you download the actual API and look for the kymoline class,there is no msd function associated with it.Simply stated, you cannot get the msd information with command like kymolines[0].msd() as stated in the first link.It looks like really useful tool.Could you update the API or let me know how to get this function up and running?

**Comment by JoepVanlier** [comment]
Hi, thanks for reaching  out! That feature will be in release v0.9.0.

The docs page you linked is for the `latest` version (which is the unreleased version currently on GitHub). If you select `stable`, in the docs dropdown, you see the latest stable release.

I'll reply here when we release v0.9.0.

**Comment by spangeni** [comment]
Okay cool.Any estimate on when?

**Comment by JoepVanlier** [comment]
We just released Pylake `v0.9.0`, which includes the MSD plotting functionality.
