### ISSUE TITLE
ImportError on Python 3.10

### ISSUE THREAD

**Issue by b-dawes** [lumicks/pylake#266]
The pylake package currently depends on tabulate 0.8.6 (at least on conda). However, this version of tabulate is [incompatible with python 3.10](https://github.com/astanin/python-tabulate/issues/104) (the reason is rather silly, they were comparing the python version number as a string so "10"<"3").  Because of this, importing either lumicks.pylake or tabulate on python 3.10 throws an ImportError. 

[The fix](https://github.com/astanin/python-tabulate/commit/24625986d76b50abea7cdce45f62861e72cff2b6) was implemented in tabulate 0.8.8 (current release is 0.8.9).

**Comment by JoepVanlier** [comment]
Thanks for bringing this to our attention (and the detailed report of the issue)! We'll bump the requirement in the next release.

**Comment by rpauszek** [comment]
`pylake v0.11.1` has now been released and adds support for `python 3.10`
