### ISSUE TITLE
FileNotFoundError in Kymograph and Force notebook

### ISSUE THREAD

**Issue by karlduderstadt** [lumicks/pylake#284]
First of all, thanks for creating this cool open resource in python to help getting started with LUMICKs data. 

I just installed lumicks.pylake and figured I would start by running the Kymograph and Force notebook. But right away, I get a FileNotFoundError when trying to load the Sytox kymograph data. See below:
<img width="1080" alt="Screenshot 2022-03-29 at 12 20 48" src="https://user-images.githubusercontent.com/17951396/160590690-3c951e9b-6754-4e2b-a903-97156d937c83.png">

I looked around and I can't find the file '20181107-152940 Sytox kymograph 7.h5' anywhere in the repo. Is this file available somewhere so I could test out that notebook? Would be really helpful to see how the basic analysis is performed.

Or is there any sample data available from any papers that have been published using a LUMICKS system? I looked around a bit but don't seem to find any.

Thanks a lot!!

**Comment by mikhas** [comment]
The data files mentioned in the notebooks from the `examples` directory are meant as placeholders and assume you have already run C-Trap experiments on your own.

Currently, the best way to get example `.h5` files is via Lumicks' Harbor platform: https://harbor.lumicks.com/
Sadly, the platform requires signup/login to download any of the Jupyter notebooks. Some of them will contain datasets, for instance:

1. Force-Distance curves: https://harbor.lumicks.com/single-script/5586fed3-7e3b-4aa5-baba-c49548e3d54a
2. Kymographs: https://harbor.lumicks.com/single-script/d4680225-4abf-4846-8a00-f91ba0f4d6b3

Both zip archives contain a `Data` directory with `.h5` files.

**Comment by karlduderstadt** [comment]
Whoa! Thanks for the super fast reply and very helpful links. I already made an account on harbor and checked out those datasets. The kymotracker widget looks really cool! This will work great to get me started. 

We were hoping to create a rough LUMICKS h5 importer for our software platform because the reviewers of [our paper](https://www.biorxiv.org/content/10.1101/2021.11.26.470105v2) asked for this interoperability. But as far as I can tell, the license for the file you linked only allow personal use for those data, so we wouldn't be able to include them (with attribution) for people to prototype our importer. 

I agreed with the other issue you linked. It is really sad there isn't any publicly available dataset for people to learn from. In fact, to be quick honest this is shocking. If we had a C-trap we would collect some for you and allow you full re-use of it.

Anyway, I will go ahead and close this issue and I guess I have to contact someone directly for some simple sample data.

Thanks again for your very helpful response!!

**Comment by mikhas** [comment]
FYI, there are now example datasets on Zenodo:
https://zenodo.org/search?page=1&size=20&q=%22Pylake%20tutorial%20dataset%22&type=dataset
