### ISSUE TITLE
Issue with Correlating Timestamps of a Multiple Image Scan

### ISSUE THREAD

**Issue by watters16j** [lumicks/pylake#35]
When reading a multiple image scan file, I would like to have a way to get a timestamp for an individual scan that is linked to the timestamps of the "Force HF" timestamps. I haven't found anything in the documentation regarding this for multiple image scans (or for single scans relating the scanning time of the image to the larger time scale of the force data), since it seems like the timestamps method of the scan file type returns the timing of the image capture process.

I initially thought finding the minimum and maximum of each individual scan's timestamp array would give a minimum and maximum time, but that seems to calculate the time it took to raster through each scan (code below). Is there anything that has the functionality that I want prebuilt in the pylake library? I apologize if the issues tab is the wrong place to put this query.

`
import numpy
from lumicks import pylake

h5file = pylake.File("pathToH5file.h5")

scan = h5file.scans["18"]
numberFrames = int(scan.num_frames)

totalTimeStampArray = scan.timestamps
minTotal = numpy.amin(totalTimeStampArray)
print('Frame Number\tMinimum Time(s)\tMaximum Time(s)')
for i in range(0,numberFrames-1):
    timestampArray = scan.timestamps[i,:,:]
    minTime = (numpy.amin(timestampArray)-minTotal) / 1000000000
    maxTime = (numpy.amax(timestampArray)-minTotal) / 1000000000
    print(f'Frame {i+1}\t{minTime}\t{maxTime}')
`

**Comment by JoepVanlier** [comment]
Hi! I'm not entirely sure if I understand the question correctly, but please correct me if I'm not actually answering your question.

The timestamps are defined on the same time axis. If you want to use the time stamps to grab the corresponding force over the image time, you shouldn't subtract the timestamp of the start of the scan. Note that the timestamps you get with scan.timestamps are the mean of the timestamps within that pixel's acquisition window.

You were on the right track though, the following is how you could average force over the scan time.
```python
import numpy as np
from lumicks import pylake
import matplotlib.pyplot as plt

h5file = pylake.File("file_name.h5")
_, scan = h5file.scans.popitem()

avg_force = []
timestamps = scan.timestamps
numberFrames = int(scan.num_frames)
for i in range(numberFrames):
    minTime = np.min(timestamps[i, :, :]).astype(np.int64)
    maxTime = np.max(timestamps[i, :, :]).astype(np.int64)

    # Slice directly with the timestamp values
    f = np.mean(h5file["Force LF"]["Force 1x"][minTime : maxTime].data)
    avg_force.append(f)

plt.figure()
plt.plot(range(1, numberFrames + 1), avg_force)
plt.xlabel('Frame [#]')
plt.ylabel('Averaged Force [pN]')
plt.show()
```

You could also use `downsampled_over` which allows you to write this in a more succinct format:
```python
timestamps = scan.timestamps
ranges = [
    (
        np.min(timestamps[i, :, :]).astype(np.int64),
        np.max(timestamps[i, :, :]).astype(np.int64),
    )
    for i in range(numberFrames)
]
avg_force2 = h5file["Force LF"]["Force 1x"].downsampled_over(ranges)
plt.plot(avg_force2.data)
```

P.S. One minor thing I noticed as well is that you subtract the minimum of all the scan timestamps, which is zero if any scan has been partial. If you want the first timestamp, just take scan.timestamps[0, 0, 0]

**Comment by watters16j** [comment]
Thanks so much for your help. The P.S. note helped out a ton!
