### ISSUE TITLE
Pylake Version 13.1 does not display the tracking widget

### ISSUE THREAD

**Issue by spangeni** [lumicks/pylake#391]
I recently update the pylake version to 13.1 but the tracing window is not dispalyed. I tried to update and downgrade matplotlib which did not help. Downgrading the pylake to version 12 however seems to solver the issue. 
Here is the screenshot.
Note:scripts are run in latests version of the VS Code.
<img width="932" alt="Pylake _issue_version_13 1" src="https://user-images.githubusercontent.com/66917473/193327470-52fc9b86-7f4c-4d06-83ec-f7671d4fbe81.PNG">

**Comment by rpauszek** [comment]
Hello, thanks for bringing this to our attention. I just tested again on my system and the widget works as expected using `jupyter notebook` (browser based) and also displays when I use VS Code, although the layout is not what it should be.

Would you mind trying `v0.13.1` with the browser version to see if it works? This could help us pinpoint where exactly the problem might be. I suspect it might be specifically with the `%matplotlib widget` backend versus `%matplotlib notebook`

**Comment by mikhas** [comment]
How did you install Pylake? Did you use `conda` or `pip`? Starting with `v0.13.0` the notebook dependencies have been marked as optional (if you are using `pip`). This should do the trick:
```
$> pip install lumicks.pylake[notebook]
```

More details here: https://lumicks-pylake.readthedocs.io/en/stable/install.html

**Comment by spangeni** [comment]
i do use conda for the installation.I have no issue in the browser as well. Issue seems to be VS code specific. Notebook backend also does not help. I am simply switching to the browser while I troubleshhot the VS code.Thanks

**Comment by mikhas** [comment]
Perhaps VS Code is not picking up the correct conda environment? See https://code.visualstudio.com/docs/python/environments#_conda-environments

**Comment by JoepVanlier** [comment]
Another thing that may be worth checking is which version of `ipywidgets` you are running. VSCode only supports ipywidgets up to `7.x` at the moment. See: https://github.com/microsoft/vscode-jupyter/issues/8552
